package com.horsetransport.document;

public enum DocumentType {
	HORSE_PASSPORT_OR_IDENTIFICATION,
	VACCINATION_CERTIFICATE,
	VETERINARY_HEALTH_CERTIFICATE,
	OWNERSHIP_CERTIFICATE,
	EXPORT_IMPORT_PERMIT
}
